jobs:
  main:
    image: docker-registry.corp.yahoo.co.jp:4443/ynodejs/v6-thin:1-STABLE
    steps:
      - init: npm install
      - test: npm test
      - pack: npm pack
      - printenv: printenv
      - mv: mv screwdriver-sd-test-0.0.1.tgz $SD_ARTIFACTS_DIR
      - meta_set: /opt/sd/meta set foo bar && echo $?
      - meta_get: /opt/sd/meta get foo
      - cat: cat /sd/meta/meta.json
