jobs:
  main:
    image: node:6
    steps:
      - init: npm install
      - test: npm test
      - pack: npm pack
      - printenv: printenv
      - mv: mv screwdriver-sd-test-0.0.1.tgz $SD_ARTIFACTS_DIR
      - sleep: sleep 10000
      - set: meta set foo bar && echo $? 
      - get: meta get foo
  next:
    image: node:6-wheezy
    steps:
      - get: meta get foo && echo $? 
      - cat: cat /sd/meta/meta.json && echo $? 
      - sleep2: sleep 10000
